CREATE TABLE nba_table (
ID INT PRIMARY KEY,
Team VARCHAR(255),
Game VARCHAR(255),
Date DATE NOT NULL,
Home VARCHAR(255),
Opponent VARCHAR(255),
WINorLOSS VARCHAR(255),
TeamPoints INT,
OpponentPoints INT,
FieldGoals INT,
FieldGoalsAttempted INT,
FieldGoals_pct DECIMAL,
X3PointShots INT,
X3PointShotsAttempted INT,
X3PointShots_pct DECIMAL,
FreeThrows INT,
FreeThrowsAttempted INT,
FreeThrows_pct DECIMAL,
OffRebounds INT,
TotalRebounds INT,
Assists INT,
Steals INT,
Blocks INT,
Turnovers INT,
TotalFouls INT,
OppFieldGoals INT,
OppFieldGoalsAttempted INT,
OppFieldGoals_pct DECIMAL,
Opp3PointShots INT,
Opp3PointShotsAttempted INT,
Opp3PointShots_pct DECIMAL,
OppFreeThrows INT,
OppFreeThrowsAttempted INT,
OppFreeThrows_pct DECIMAL,
OppOffRebounds INT,
OppTotalRebounds INT,
OppAssists INT,
OppSteals INT,
OppBlocks INT,
OppTurnovers INT,
OppTotalFouls INT
);

SELECT * FROM nba_table;